services:
  # Individual PostgreSQL instances for each service
  appointments_db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: appointments_development
    volumes:
      - appointments_postgres_data:/var/lib/postgresql/data
    ports:
      - "5442:5432"

  communications_db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: communications_development
    volumes:
      - communications_postgres_data:/var/lib/postgresql/data
    ports:
      - "5443:5432"

  log_db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: log_development
    volumes:
      - log_postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"

  patient_records_db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: patient_records_development
    volumes:
      - patient_records_postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5432"

  users_db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users_development
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    ports:
      - "5446:5432"

  video_calls_db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: video_calls_development
    volumes:
      - video_calls_postgres_data:/var/lib/postgresql/data
    ports:
      - "5447:5432"

  doctor_details_db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: doctor_details_development
    volumes:
      - doctor_details_postgres_data:/var/lib/postgresql/data
    ports:
      - "5448:5432"

  # Shared Redis instance
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  appointments_sidekiq:
    build:
      context: ./services/appointments_service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - .:/appointments_sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - appointments_db
      - redis

  communications_sidekiq:
    build:
      context: ./services/communications_service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - .:/communications_sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - communications_db
      - redis

  # Application services
  appointments:
    build:
      context: ./services/appointments_service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - appointments_db
      - redis
    ports:
      - "3001:3000"

  communications:
    build:
      context: ./services/communications_service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - communications_db
      - redis
    ports:
      - "3002:3000"

  log:
    build:
      context: ./services/log_service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - log_db
      - redis
    ports:
      - "3003:3000"

  patient_records:
    build:
      context: ./services/patient_records_service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - users
      - patient_records_db
      - redis
    ports:
      - "3004:3000"

  users:
    build:
      context: ./services/users_service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - users_db
      - redis
    ports:
      - "3005:3000"

  video_calls:
    build:
      context: ./services/video_calls_service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - video_calls_db
      - redis
    ports:
      - "3006:3000"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - appointments
      - communications
      - log
      - patient_records
      - users
      - video_calls
    ports:
      - "3007:3000"

  doctor_details:
    build:
      context: ./services/doctor_details_service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - users
      - doctor_details_db
      - redis
    ports:
      - "3008:3000"

volumes:
  appointments_postgres_data:
  communications_postgres_data:
  log_postgres_data:
  patient_records_postgres_data:
  doctor_details_postgres_data:
  users_postgres_data:
  video_calls_postgres_data:
  redis_data:
  patient_uploads:
